### ISSUE TITLE
Dice calculation arguments wrong way around

### ISSUE THREAD

**Issue by rensdebee** [HKervadec/ai4mi_project#1]
I was looking at implementing new metrics for our project and analyzed the code for the dice calculation.
There I noticed when the `dice_coef` function is called it is called with `dice_coef(pred_seg, gt)`. However the meta function which is called is defined as `meta_dice(sum_str: str, label: Tensor, pred: Tensor, smooth: float = 1e-8) -> Tensor:`. Notice how here the prediction and label arguments are switched around compared to the `dice_coef` call. I don't think this is correct but it probably won't matter for the result as the intersection and sum stay the same.

**Comment by HKervadec** [comment]
Good point, 10 points for Griffindor. Fixed in 26d2f61
